<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CustomCodeFramework.Core" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Messaging" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Auth" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Auth.Redis" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Redis" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Redis.Streams" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Mongo" Version="0.2.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.24.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dhole.Storage.Application\Dhole.Storage.Application.csproj" />
    <ProjectReference Include="..\Dhole.Storage.Contracts\Dhole.Storage.Contracts.csproj" />
  </ItemGroup>

</Project>
